
require:
  - rubocop-rspec

Metrics/BlockLength:
  ExcludedMethods: ['context', 'describe']
  
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: separator

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space

Style/CharacterLiteral:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true
